### ISSUE TITLE
Can't export all steps in portal_setup if archetypes.multilingual is available

### ISSUE THREAD

**Issue by idgserpro** [plone/archetypes.multilingual#27]
Minimal buildout for testing:

```
[buildout]
parts = instance
extends = https://dist.plone.org/release/4-latest/versions.cfg
index = https://pypi.org/simple/
versions = versions

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs =
    Plone
    Pillow
    plone.app.contenttyoes=1.1.6
    plone.app.multilingual==2.0.4
    archetypes.multilingual==2.1.0
```
Create a Plone site and install the three packages above.

Clicking in "Export all steps" in `portal_setup` gives the following traceback:

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.GenericSetup.tool, line 655, in manage_exportAllSteps
Module Products.GenericSetup.tool, line 408, in runAllExportSteps
Module Products.GenericSetup.tool, line 1268, in _doRunExportSteps
Module Products.GenericSetup.components, line 562, in exportComponentRegistry
Module Products.GenericSetup.utils, line 498, in _exportBody
Module Products.GenericSetup.components, line 71, in _exportNode
Module Products.GenericSetup.components, line 439, in _extractHandlers
Module Products.GenericSetup.utils, line 65, in _getDottedName
ValueError: Cannot compute dotted name: <archetypes.multilingual.subscriber.LanguageIndependentModifier object at 0x7f569a1c20d0>
```

It happens in `
**Local Component Registry**
Export local component registry configuration.  Products.GenericSetup.components.exportComponentRegistry`

**Comment by idgserpro** [comment]
The same error happens if you go to `manage_components` in the `ZMI`.

**Comment by idgserpro** [comment]
@mauritsvanrees have any idea why this happens?

**Comment by mauritsvanrees** [comment]
I see the same in a much older client site (Plone 4.3.3) with archetypes.multilingual 1.2.
With a pdb in `GenericSetup`:

```
2019-08-02 10:29:22 INFO GenericSetup.componentregistry Adapters exported.
> /Users/maurits/shared-eggs/Products.GenericSetup-1.7.4-py2.7.egg/Products/GenericSetup/utils.py(66)_getDottedName()
-> raise ValueError('Cannot compute dotted name: %s' % named)
(Pdb) 
(Pdb) 
(Pdb) 
(Pdb) l
 61  	
 62  	    try:
 63  	        dotted = '%s.%s' % (named.__module__, named.__name__)
 64  	    except AttributeError:
 65  	        import pdb; pdb.set_trace()
 66  ->	        raise ValueError('Cannot compute dotted name: %s' % named)
 67  	
 68  	    # remove leading underscore names if possible
 69  	
 70  	    # Step 1: check if there is a short version
 71  	    short_dotted = '.'.join([ n for n in dotted.split('.')
(Pdb) a
named = <archetypes.multilingual.subscriber.LanguageIndependentModifier object at 0x10cbfa650>
(Pdb) named
<archetypes.multilingual.subscriber.LanguageIndependentModifier object at 0x10cbfa650>
(Pdb) named.__module__
'archetypes.multilingual.subscriber'
(Pdb) named.__name__
*** AttributeError: 'LanguageIndependentModifier' object has no attribute '__name__'
```

It iterates over these handlers:

```
(Pdb) pp list(self.context.registeredHandlers())
[HandlerRegistration(<PersistentComponents /Plone>, [ITranslatable, IObjectModifiedEvent], u'', update_on_modify, u''),
 HandlerRegistration(<PersistentComponents /Plone>, [ITranslatable, IObjectAddedEvent], u'', createdEvent, u''),
 HandlerRegistration(<PersistentComponents /Plone>, [ITranslatable, IObjectCopiedEvent], u'', createdEvent, u''),
 HandlerRegistration(<PersistentComponents /Plone>, [ITranslatable, IObjectMovedEvent], u'', createdEvent, u''),
 HandlerRegistration(<PersistentComponents /Plone>, [IArchetypesTranslatable, IObjectModifiedEvent], u'', <archetypes.multilingual.subscriber.LanguageIndependentModifier object at 0x10cbfa650>, u''),
 HandlerRegistration(<PersistentComponents /Plone>, [IDexterityTranslatable, IObjectModifiedEvent], u'', <plone.multilingualbehavior.subscriber.LanguageIndependentModifier object at 0x10c7376d0>, u'')]
```

The `_getDottedName` function expects a function, or maybe a class, but it gets an instance here.  It goes wrong for the last one in the list too, in `plone.multilingualbehavior`.

The registration is done in https://github.com/plone/archetypes.multilingual/blob/v1.2/archetypes/multilingual/profiles/default/componentregistry.xml#L16-L20

It registers [`archetypes.multilingual.subscriber.handler`](https://github.com/plone/archetypes.multilingual/blob/v1.2/archetypes/multilingual/subscriber.py#L69) as subscriber.
I wonder if it could be fixed by changing that handler in the code:

```
# Old:
# handler = LanguageIndependentModifier()
# New:
_handler = LanguageIndependentModifier()

def handler(content, event):
    return _handler(content, event)
```

**Comment by mauritsvanrees** [comment]
That may require an upgrade step though, because the current handler is stored in the database. Not sure. After such a change, the `handler` still points to something, it is just something different.

**Comment by mauritsvanrees** [comment]
I notice the same behavior still in Plone 5.2 with Archetypes. When I use the code I give above and then create a a new site, all is well. But not for an existing site: there the named subscriber still points to an instance of the `LanguageIndependentModifier` class.

Setting `handler.__name__ = "LanguageIndependentModifier"` in this file does not work either. Doing it in a pdb *does* help for a moment, but the change is not persisted. Can probably be worked around.

[Background: I am trying to migrate a Plone 4.3 site with Archetypes and plone.app.multilingual 1 to 5.2 and am running into various multilingual issues. This is one of them, or at least it does not help.]

**Comment by mauritsvanrees** [comment]
For others that are migrating from plone.app.multilingual 1.x, see [upgrade notes](https://github.com/plone/plone.app.multilingual/issues/181#issuecomment-141661848). I have not tried them yet.

Also, plone.multilingualbehavior has an [uninstall profile](https://github.com/plone/plone.multilingualbehavior/pull/9) that may be useful for archetypes.multilingual as well. And parts of that code may be useful for an upgrade step to fix the above problem.

**Comment by mauritsvanrees** [comment]
Adding this to the class helps:

```
    @property
     def __name__(self):
         return "handler"
```

That is what `plone.multilingualbehavior` does since [PR 8](https://github.com/plone/plone.multilingualbehavior/pull/8) and that I further improved in [PR 10](https://github.com/plone/plone.multilingualbehavior/pull/10).

PRs for `archetypes.multilingual`:
- 1.x: https://github.com/plone/archetypes.multilingual/pull/29
- 2.x: https://github.com/plone/archetypes.multilingual/pull/30
- master: https://github.com/plone/archetypes.multilingual/pull/31

**Comment by mauritsvanrees** [comment]
Fixed in `plone.multilingualbehavior` 1.2.3, and in `archetypes.multilingual` 1.3.0, 2.1.2, and 3.0.8.
